### PR TITLE
Dashboard overview cards should match up with mockups

### PR DESCRIPTION
**Pull request by helenm1**
## Description/Problem

Closes [Dashboard overview cards should match up with mockups](https://trello.com/c/AmlSzmwc)

## Solution

- Removed grey border from cards to reflect Figma design of dashboard (overview)
- Added AvatarGroup spacing and margin for Avatar
- Imported correct font weight for formName

## Dependencies

[X] This PR adds new dependencies

## Testing

Did manual testing on common browsers (Chrome, Safari, Firefox)

original:
image

updated:
image  

figma screenshot:
image

### CODE REVIEW

**Review by elvincheng3 — COMMENTED** [review]
Could we also look into the overlapping avatars and the text/avatar to card scaling?

**Comment by helenm1** [comment]
the order of avatar overlapping is in reverse compared to the design but not sure if it can be reversed with Chakra?

**Comment by elvincheng3** [comment]
> the order of avatar overlapping is in reverse compared to the design but not sure if it can be reversed with Chakra?

i think that's minor, i don't think the ordering is significant

**Review by elvincheng3 — APPROVED** [review]
Looks great!

**Pull request merged**
